export interface Game {
  id: number
  first_blood_team_id: number
  first_turret_team_id: number
  date: Date
  created_at: Date
  updated_at: Date
  winner_id: number
  loser_id: number
  red_side_team_id: number
  blue_side_team_id: number
  first_baron_team_id: number
  first_dragon_team_id: number
  first_turret_player_id: number
  first_dragon_player_id: number
  first_baron_player_id: number
  first_blood_player_id: number
  first_turret_type?: number
  first_dragon_time?: number
  first_blood_time?: number
  first_turret_time?: number
  first_baron_time?: number
  league_id?: number
  gameid?: number
  split_id?: number
  fb_odds?: number
  ft_odds?: number
  fd_odds?: number
  fbaron_odds?: number
  red_side_team_fb_odds?: number
  red_side_team_ft_odds?: number
  red_side_team_fd_odds?: number
  red_side_team_fbaron_odds?: number
  red_side_team_win_odds?: number
  blue_side_team_fb_odds?: number
  blue_side_team_ft_odds?: number
  blue_side_team_fd_odds?: number
  blue_side_team_fbaron_odds?: number
  blue_side_team_win_odds?: number
  blue_side_win_odds?: number
  red_side_win_odds?: number
  game_number?: number
  match_uuid?: string
}
