export interface Game {
  id: number
  firstBloodTeamId?: number
  firstTurretTeamId?: number
  date: Date
  createdAt: Date
  updatedAt: Date
  winnerId?: number
  loserId?: number
  redSideTeamId: number
  blueSideTeamId: number
  firstBaronTeamId?: number
  firstDragonTeamId?: number
  firstTurretPlayerId?: number
  firstDragonPlayerId?: number
  firstBaronPlayerId?: number
  firstBloodPlayerId?: number
  firstTurretType?: number
  firstDragonTime?: number
  firstBloodTime?: number
  firstTurretTime?: number
  firstBaronTime?: number
  leagueId?: number
  gameid?: number
  splitId?: number
  fbOdds?: number
  ftOdds?: number
  fdOdds?: number
  fbaronOdds?: number
  redSideTeamFbOdds?: number
  redSideTeamFtOdds?: number
  redSideTeamFdOdds?: number
  redSideTeamFbaronOdds?: number
  redSideTeamWinOdds?: number
  blueSideTeamFbOdds?: number;
  blueSideTeamFtOdds?: number
  blueSideTeamFdOdds?: number
  blueSideTeamFbaronOdds?: number
  blueSideTeamWinOdds?: number
  blueSideWinOdds?: number
  redSideWinOdds?: number
  gameNumber?: number
  matchUuid?: string
}
